CREATE TYPE "tipo_tarjeta" AS ENUM (
  'amarilla',
  'roja'
);

CREATE TYPE "seccion_aparicion" AS ENUM (
  'titular',
  'ingresado',
  'suplente_no_jugo',
  'entrenador'
);

CREATE TYPE "tipo_destinatario_premio" AS ENUM (
  'jugador',
  'seleccion'
);

CREATE TYPE "rol_plantel" AS ENUM (
  'jugador',
  'entrenador'
);

CREATE TYPE "source_table_resolucion" AS ENUM (
  'gol',
  'tarjeta',
  'cambio_entrada',
  'cambio_salida',
  'aparicion_partido',
  'penal'
);

CREATE TABLE "mundial" (
  "anio" integer PRIMARY KEY,
  "sede" text,
  "campeon" text,
  "subcampeon" text,
  "tercer_lugar" text,
  "cuarto_lugar" text,
  "equipos" integer,
  "partidos_jugados" integer,
  "goles_total" integer,
  "promedio_gol" decimal(6,2)
);

CREATE TABLE "seleccion" (
  "seleccion_id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "slug" text UNIQUE NOT NULL,
  "nombre" text NOT NULL,
  "participaciones" integer,
  "pj" integer,
  "pg" integer,
  "pe" integer,
  "pp" integer,
  "gf" integer,
  "gc" integer,
  "titulos" integer,
  "subcampeonatos" integer,
  "posicion_historica" text
);

CREATE TABLE "seleccion_alias" (
  "alias_slug" text PRIMARY KEY,
  "alias_nombre" text NOT NULL,
  "seleccion_id" bigint NOT NULL,
  "notas" text
);

CREATE TABLE "jugador" (
  "jugador_id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "slug" text UNIQUE,
  "nombre" text NOT NULL,
  "nombre_completo" text,
  "seleccion_nombre" text,
  "seleccion_id" bigint,
  "fecha_nacimiento" text,
  "lugar_nacimiento" text,
  "posicion" text,
  "numeros_camiseta" text,
  "altura" text,
  "apodo" text,
  "sitio_web" text,
  "redes_sociales" text,
  "mundiales" integer,
  "partidos" integer,
  "goles" integer,
  "promedio_gol" decimal(6,2)
);

CREATE TABLE "partido" (
  "partido_id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "slug" text UNIQUE NOT NULL,
  "anio" integer NOT NULL,
  "fecha" text,
  "etapa" text,
  "local_nombre" text NOT NULL,
  "visitante_nombre" text NOT NULL,
  "local_seleccion_id" bigint,
  "visitante_seleccion_id" bigint,
  "resultado" text,
  "tiempo_extra" boolean,
  "penales" boolean,
  "resultado_penales" text
);

CREATE TABLE "aparicion_partido" (
  "aparicion_id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "partido_slug" text NOT NULL,
  "anio" integer NOT NULL,
  "equipo_nombre" text NOT NULL,
  "seleccion_id" bigint,
  "jugador_slug" text,
  "jugador_id" bigint,
  "jugador_nombre" text NOT NULL,
  "posicion" text,
  "camiseta" text,
  "seccion" seccion_aparicion NOT NULL,
  "es_capitan" boolean NOT NULL DEFAULT false
);

CREATE TABLE "gol" (
  "gol_id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "partido_slug" text NOT NULL,
  "anio" integer NOT NULL,
  "equipo_nombre" text NOT NULL,
  "seleccion_id" bigint,
  "jugador" text NOT NULL,
  "jugador_slug" text,
  "jugador_id" bigint,
  "minuto" text,
  "es_penal" boolean NOT NULL DEFAULT false,
  "es_autogol" boolean NOT NULL DEFAULT false
);

CREATE TABLE "tarjeta" (
  "tarjeta_id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "partido_slug" text NOT NULL,
  "anio" integer NOT NULL,
  "jugador" text NOT NULL,
  "jugador_slug" text,
  "jugador_id" bigint,
  "equipo_nombre" text NOT NULL,
  "seleccion_id" bigint,
  "tipo" tipo_tarjeta NOT NULL,
  "minuto" text
);

CREATE TABLE "cambio" (
  "cambio_id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "partido_slug" text NOT NULL,
  "anio" integer NOT NULL,
  "equipo_nombre" text NOT NULL,
  "seleccion_id" bigint,
  "sale" text,
  "sale_slug" text,
  "sale_jugador_id" bigint,
  "entra" text,
  "entra_slug" text,
  "entra_jugador_id" bigint,
  "minuto" text
);

CREATE TABLE "penal" (
  "penal_id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "partido_slug" text NOT NULL,
  "anio" integer NOT NULL,
  "equipo_nombre" text NOT NULL,
  "seleccion_id" bigint,
  "orden" integer NOT NULL,
  "jugador" text NOT NULL,
  "jugador_slug" text,
  "jugador_id" bigint,
  "resultado" text NOT NULL
);

CREATE TABLE "grupo" (
  "grupo_id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "anio" integer NOT NULL,
  "grupo" text NOT NULL,
  "posicion" integer,
  "seleccion_nombre" text NOT NULL,
  "seleccion_id" bigint,
  "pts" integer,
  "pj" integer,
  "pg" integer,
  "pe" integer,
  "pp" integer,
  "gf" integer,
  "gc" integer,
  "dif" integer,
  "clasificado" boolean
);

CREATE TABLE "posicion_final" (
  "posicion_final_id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "anio" integer NOT NULL,
  "posicion" integer NOT NULL,
  "seleccion_nombre" text NOT NULL,
  "seleccion_id" bigint
);

CREATE TABLE "goleador" (
  "goleador_id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "anio" integer NOT NULL,
  "jugador" text NOT NULL,
  "jugador_slug" text,
  "jugador_id" bigint,
  "seleccion_nombre" text,
  "seleccion_id" bigint,
  "goles" integer
);

CREATE TABLE "premio" (
  "premio_id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "anio" integer NOT NULL,
  "premio" text NOT NULL,
  "tipo_destinatario" tipo_destinatario_premio NOT NULL,
  "jugador" text,
  "jugador_slug" text,
  "jugador_id" bigint,
  "seleccion_nombre" text,
  "seleccion_id" bigint,
  "destinatario_key" text
);

CREATE TABLE "plantel" (
  "plantel_id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "anio" integer NOT NULL,
  "seleccion_nombre" text,
  "seleccion_slug" text,
  "seleccion_key" text,
  "seleccion_id" bigint,
  "jugador" text NOT NULL,
  "jugador_slug" text,
  "jugador_key" text,
  "jugador_id" bigint,
  "posicion" text,
  "camiseta" text,
  "fecha_nacimiento" text,
  "altura" text,
  "club" text,
  "rol" rol_plantel NOT NULL
);

CREATE TABLE "participacion_mundial" (
  "participacion_id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "anio" integer NOT NULL,
  "seleccion_nombre" text NOT NULL,
  "seleccion_slug" text,
  "seleccion_key" text,
  "seleccion_id" bigint,
  "posicion" integer,
  "etapa" text,
  "pts" integer,
  "pj" integer,
  "pg" integer,
  "pe" integer,
  "pp" integer,
  "gf" integer,
  "gc" integer,
  "dif" integer,
  "participo" boolean NOT NULL DEFAULT true
);

CREATE TABLE "resolucion_identidad_jugador" (
  "resolucion_id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "source_table" source_table_resolucion NOT NULL,
  "source_pk" bigint,
  "partido_slug" text NOT NULL,
  "anio" integer NOT NULL,
  "equipo_nombre" text,
  "equipo_key" text,
  "jugador_nombre_raw" text NOT NULL,
  "jugador_slug_raw" text,
  "minuto" text,
  "minuto_key" text,
  "jugador_id_resuelto" bigint,
  "jugador_slug_resuelto" text,
  "metodo" text NOT NULL DEFAULT 'manual',
  "confianza" decimal(5,2),
  "notas" text
);

CREATE UNIQUE INDEX ON "aparicion_partido" ("partido_slug", "equipo_nombre", "jugador_nombre", "seccion");

CREATE UNIQUE INDEX ON "penal" ("partido_slug", "equipo_nombre", "orden");

CREATE UNIQUE INDEX ON "grupo" ("anio", "grupo", "seleccion_nombre");

CREATE UNIQUE INDEX ON "posicion_final" ("anio", "posicion", "seleccion_nombre");

CREATE UNIQUE INDEX ON "goleador" ("anio", "jugador", "seleccion_nombre");

CREATE UNIQUE INDEX ON "premio" ("anio", "premio", "tipo_destinatario", "destinatario_key");

CREATE UNIQUE INDEX ON "plantel" ("anio", "jugador_key", "seleccion_key", "rol");

CREATE UNIQUE INDEX ON "participacion_mundial" ("anio", "seleccion_key");

CREATE UNIQUE INDEX ON "resolucion_identidad_jugador" ("source_table", "partido_slug", "equipo_key", "jugador_nombre_raw", "minuto_key");

COMMENT ON COLUMN "premio"."destinatario_key" IS 'Generado en SQL para soportar premios a jugador o seleccion';

COMMENT ON COLUMN "plantel"."seleccion_key" IS 'Generado en SQL: coalesce(seleccion_slug, seleccion_nombre)';

COMMENT ON COLUMN "plantel"."jugador_key" IS 'Generado en SQL: coalesce(jugador_slug, jugador)';

COMMENT ON COLUMN "participacion_mundial"."seleccion_key" IS 'Generado en SQL para deduplicar por anio y seleccion';

COMMENT ON COLUMN "resolucion_identidad_jugador"."equipo_key" IS 'Generado en SQL';

COMMENT ON COLUMN "resolucion_identidad_jugador"."minuto_key" IS 'Generado en SQL';

ALTER TABLE "seleccion_alias" ADD FOREIGN KEY ("seleccion_id") REFERENCES "seleccion" ("seleccion_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "jugador" ADD FOREIGN KEY ("seleccion_id") REFERENCES "seleccion" ("seleccion_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "partido" ADD FOREIGN KEY ("anio") REFERENCES "mundial" ("anio") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "partido" ADD FOREIGN KEY ("local_seleccion_id") REFERENCES "seleccion" ("seleccion_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "partido" ADD FOREIGN KEY ("visitante_seleccion_id") REFERENCES "seleccion" ("seleccion_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "aparicion_partido" ADD FOREIGN KEY ("partido_slug") REFERENCES "partido" ("slug") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "aparicion_partido" ADD FOREIGN KEY ("anio") REFERENCES "mundial" ("anio") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "aparicion_partido" ADD FOREIGN KEY ("seleccion_id") REFERENCES "seleccion" ("seleccion_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "aparicion_partido" ADD FOREIGN KEY ("jugador_slug") REFERENCES "jugador" ("slug") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "aparicion_partido" ADD FOREIGN KEY ("jugador_id") REFERENCES "jugador" ("jugador_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "gol" ADD FOREIGN KEY ("partido_slug") REFERENCES "partido" ("slug") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "gol" ADD FOREIGN KEY ("anio") REFERENCES "mundial" ("anio") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "gol" ADD FOREIGN KEY ("seleccion_id") REFERENCES "seleccion" ("seleccion_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "gol" ADD FOREIGN KEY ("jugador_slug") REFERENCES "jugador" ("slug") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "gol" ADD FOREIGN KEY ("jugador_id") REFERENCES "jugador" ("jugador_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "tarjeta" ADD FOREIGN KEY ("partido_slug") REFERENCES "partido" ("slug") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "tarjeta" ADD FOREIGN KEY ("anio") REFERENCES "mundial" ("anio") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "tarjeta" ADD FOREIGN KEY ("seleccion_id") REFERENCES "seleccion" ("seleccion_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "tarjeta" ADD FOREIGN KEY ("jugador_slug") REFERENCES "jugador" ("slug") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "tarjeta" ADD FOREIGN KEY ("jugador_id") REFERENCES "jugador" ("jugador_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "cambio" ADD FOREIGN KEY ("partido_slug") REFERENCES "partido" ("slug") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "cambio" ADD FOREIGN KEY ("anio") REFERENCES "mundial" ("anio") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "cambio" ADD FOREIGN KEY ("seleccion_id") REFERENCES "seleccion" ("seleccion_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "cambio" ADD FOREIGN KEY ("sale_slug") REFERENCES "jugador" ("slug") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "cambio" ADD FOREIGN KEY ("sale_jugador_id") REFERENCES "jugador" ("jugador_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "cambio" ADD FOREIGN KEY ("entra_slug") REFERENCES "jugador" ("slug") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "cambio" ADD FOREIGN KEY ("entra_jugador_id") REFERENCES "jugador" ("jugador_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "penal" ADD FOREIGN KEY ("partido_slug") REFERENCES "partido" ("slug") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "penal" ADD FOREIGN KEY ("anio") REFERENCES "mundial" ("anio") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "penal" ADD FOREIGN KEY ("seleccion_id") REFERENCES "seleccion" ("seleccion_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "penal" ADD FOREIGN KEY ("jugador_slug") REFERENCES "jugador" ("slug") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "penal" ADD FOREIGN KEY ("jugador_id") REFERENCES "jugador" ("jugador_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "grupo" ADD FOREIGN KEY ("anio") REFERENCES "mundial" ("anio") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "grupo" ADD FOREIGN KEY ("seleccion_id") REFERENCES "seleccion" ("seleccion_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "posicion_final" ADD FOREIGN KEY ("anio") REFERENCES "mundial" ("anio") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "posicion_final" ADD FOREIGN KEY ("seleccion_id") REFERENCES "seleccion" ("seleccion_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "goleador" ADD FOREIGN KEY ("anio") REFERENCES "mundial" ("anio") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "goleador" ADD FOREIGN KEY ("jugador_slug") REFERENCES "jugador" ("slug") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "goleador" ADD FOREIGN KEY ("jugador_id") REFERENCES "jugador" ("jugador_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "goleador" ADD FOREIGN KEY ("seleccion_id") REFERENCES "seleccion" ("seleccion_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "premio" ADD FOREIGN KEY ("anio") REFERENCES "mundial" ("anio") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "premio" ADD FOREIGN KEY ("jugador_slug") REFERENCES "jugador" ("slug") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "premio" ADD FOREIGN KEY ("jugador_id") REFERENCES "jugador" ("jugador_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "premio" ADD FOREIGN KEY ("seleccion_id") REFERENCES "seleccion" ("seleccion_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "plantel" ADD FOREIGN KEY ("anio") REFERENCES "mundial" ("anio") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "plantel" ADD FOREIGN KEY ("seleccion_id") REFERENCES "seleccion" ("seleccion_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "plantel" ADD FOREIGN KEY ("jugador_slug") REFERENCES "jugador" ("slug") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "plantel" ADD FOREIGN KEY ("jugador_id") REFERENCES "jugador" ("jugador_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "participacion_mundial" ADD FOREIGN KEY ("anio") REFERENCES "mundial" ("anio") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "participacion_mundial" ADD FOREIGN KEY ("seleccion_id") REFERENCES "seleccion" ("seleccion_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "resolucion_identidad_jugador" ADD FOREIGN KEY ("partido_slug") REFERENCES "partido" ("slug") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "resolucion_identidad_jugador" ADD FOREIGN KEY ("anio") REFERENCES "mundial" ("anio") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "resolucion_identidad_jugador" ADD FOREIGN KEY ("jugador_id_resuelto") REFERENCES "jugador" ("jugador_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "resolucion_identidad_jugador" ADD FOREIGN KEY ("jugador_slug_resuelto") REFERENCES "jugador" ("slug") DEFERRABLE INITIALLY IMMEDIATE;
